title: CELLAXON
author: Sanghyo Lee
email: ryan@cellaxon.com
description: >-
  CELLAXON Inc.

social:
  github: cellaxon
  linkedin: cellaxon

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
