title: CELLAXON Inc.
author: Sanghyo Lee
email: ryan@cellaxon.com
description: >-
  Address: 202-2409, 142, Dongtangambaesan-ro, Hwaseong-si, Gyeonggi-do, Republic of Korea
  Phone: +82-31-8043-3215
  Fax: +82-31-8043-3216

social:
  github: cellaxon
  linkedin: cellaxon

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
