export type Language = "en" | "ko";

export const copy = {
  en: {
    nav: {
      products: "Products",
      exploring: "Exploring",
      company: "Company",
      contact: "Contact",
      menu: "Open navigation",
      close: "Close navigation",
    },
    hero: {
      titleLead: "Complex systems,",
      titleAccent: "made visible.",
      body: "CELLAXON builds software for explicit decisions, local intelligence, and verifiable operations.",
      primary: "Explore our products",
      secondary: "Discuss a PoC",
      visualAlt: "An abstract neural signal in CELLAXON's coral, magenta, and violet colors.",
    },
    products: {
      availableLabel: "Available now",
      validationLabel: "In validation",
      ranvierSubtitle: "Typed Decision Engine for Rust",
      ranvierStatement: "Every decision visible. Every branch auditable.",
      ranvierPrimary: "Explore Ranvier",
      devpulseSubtitle: "Local-first developer intelligence for VS Code.",
      devpulsePrimary: "View Cellaxon DevPulse in the VS Code Marketplace",
    },
    flightops: {
      label: "Exploring / FlightOps",
      title: "Operational evidence for high-trust field work.",
      body: "Currently in concept validation. FlightOps is being evaluated as a product family for verifiable operational records and reporting.",
      status: "Concept validation",
      action: "Discuss a PoC",
    },
    company: {
      label: "Company",
      title: "Software with explicit boundaries.",
      body: "CELLAXON is a software company in Hwaseong, Republic of Korea. We build focused products for decisions, developer workflows, and operational evidence.",
      addressLabel: "Address",
      address: "202-2409, 143, Dongtangambaesan-ro, Hwaseong-si, Gyeonggi-do, Republic of Korea",
      emailLabel: "Email",
      phoneLabel: "Phone",
      linksLabel: "Elsewhere",
      shortcuts: "Shortcuts",
      blog: "Blog",
      linkedin: "LinkedIn",
    },
    footer: {
      line: "Complex work, made understandable.",
      copyright: "© 2026 CELLAXON. All rights reserved.",
    },
  },
  ko: {
    nav: {
      products: "제품",
      exploring: "검토 중",
      company: "회사",
      contact: "문의",
      menu: "내비게이션 열기",
      close: "내비게이션 닫기",
    },
    hero: {
      titleLead: "복잡한 시스템을,",
      titleAccent: "보이게.",
      body: "CELLAXON은 명시적 의사결정, 로컬 인텔리전스, 검증 가능한 운영을 위한 소프트웨어를 만듭니다.",
      primary: "제품 살펴보기",
      secondary: "PoC 논의하기",
      visualAlt: "CELLAXON의 코랄, 마젠타, 바이올렛 색상으로 표현한 추상적인 신경 신호.",
    },
    products: {
      availableLabel: "이용 가능",
      validationLabel: "검증 중",
      ranvierSubtitle: "Rust를 위한 타입 기반 의사결정 엔진",
      ranvierStatement: "모든 결정을 보이게. 모든 분기를 검토 가능하게.",
      ranvierPrimary: "Ranvier 살펴보기",
      devpulseSubtitle: "VS Code를 위한 로컬 우선 개발 인텔리전스.",
      devpulsePrimary: "VS Code Marketplace에서 Cellaxon DevPulse 보기",
    },
    flightops: {
      label: "검토 중 / FlightOps",
      title: "높은 신뢰가 필요한 현장 업무를 위한 운용 증빙.",
      body: "현재 개념 검증 단계입니다. FlightOps는 검증 가능한 운용 기록과 보고서를 위한 제품군으로 사업성을 검토하고 있습니다.",
      status: "개념 검증",
      action: "PoC 논의하기",
    },
    company: {
      label: "회사",
      title: "경계가 명확한 소프트웨어.",
      body: "CELLAXON은 대한민국 화성시에 위치한 소프트웨어 회사입니다. 의사결정, 개발 워크플로, 운용 증빙을 위한 집중도 높은 제품을 만듭니다.",
      addressLabel: "주소",
      address: "경기도 화성시 동탄감배산로 143, 202동 2409호",
      emailLabel: "이메일",
      phoneLabel: "전화",
      linksLabel: "외부 링크",
      shortcuts: "바로가기",
      blog: "블로그",
      linkedin: "LinkedIn",
    },
    footer: {
      line: "복잡한 일을, 이해 가능하게.",
      copyright: "© 2026 CELLAXON. All rights reserved.",
    },
  },
} as const;
