export type Language = "en" | "ko";

export const copy = {
  en: {
    nav: {
      home: "CELLAXON home",
      primaryLabel: "Primary navigation",
      languageLabel: "Language selector",
      skip: "Skip to content",
      products: "Products",
      exploring: "Concepts",
      company: "Company",
      contact: "Contact",
      menu: "Open navigation",
      close: "Close navigation",
    },
    hero: {
      titleLead: "Complex systems,",
      titleAccent: "made visible.",
      body: "CELLAXON builds software that makes decisions transparent and keeps development and field records trustworthy.",
      primary: "Explore our products",
      secondary: "Discuss a pilot",
      visualAlt: "An abstract neural signal in CELLAXON's coral, magenta, and violet colors.",
    },
    products: {
      availableLabel: "Available now",
      validationLabel: "Under review",
      ranvierSubtitle: "Typed Decision Engine for Rust",
      ranvierStatement: "Every decision visible. Every branch auditable.",
      ranvierPrimary: "Explore Ranvier",
      devpulseSubtitle: "A VS Code extension that analyzes development data without sending it outside your environment.",
      devpulsePrimary: "View Cellaxon DevPulse in the VS Code Marketplace",
    },
    flightops: {
      label: "Under review / FlightOps",
      title: "Reliable records for high-trust field operations.",
      body: "Currently in concept validation. FlightOps is being evaluated as a product family for verifiable operational records and reporting.",
      status: "Concept review",
      action: "Discuss a pilot",
    },
    company: {
      label: "Company",
      title: "We make complex problems clear.",
      body: "CELLAXON is a software company based in Hwaseong, Korea. We build products that make complex decisions, development work, and field operations easier to understand and verify.",
      addressLabel: "Address",
      address: "202-2409, 143, Dongtangambaesan-ro, Hwaseong-si, Gyeonggi-do, Republic of Korea",
      emailLabel: "Email",
      phoneLabel: "Phone",
      linksLabel: "Elsewhere",
      shortcuts: "Shortcuts",
      blog: "Blog",
      linkedin: "LinkedIn",
    },
    footer: {
      line: "Complex work, made clear.",
      copyright: "© 2026 CELLAXON. All rights reserved.",
    },
  },
  ko: {
    nav: {
      home: "CELLAXON 홈",
      primaryLabel: "주요 메뉴",
      languageLabel: "언어 선택",
      skip: "본문으로 건너뛰기",
      products: "제품",
      exploring: "사업 검토",
      company: "회사 소개",
      contact: "문의",
      menu: "내비게이션 열기",
      close: "내비게이션 닫기",
    },
    hero: {
      titleLead: "복잡한 시스템을",
      titleAccent: "한눈에.",
      body: "CELLAXON은 의사결정 과정을 투명하게 만들고, 개발과 현장의 기록을 신뢰할 수 있게 하는 소프트웨어를 만듭니다.",
      primary: "제품 살펴보기",
      secondary: "PoC 문의하기",
      visualAlt: "CELLAXON의 코랄·마젠타·바이올렛 색상으로 표현한 추상적인 신경 신호.",
    },
    products: {
      availableLabel: "공개 제품",
      validationLabel: "사업 검토 중",
      ranvierSubtitle: "Rust로 만든 타입 기반 의사결정 엔진",
      ranvierStatement: "모든 결정과 분기를 코드에 명확하게 남깁니다.",
      ranvierPrimary: "Ranvier 살펴보기",
      devpulseSubtitle: "개발 데이터를 외부로 보내지 않고 분석하는 VS Code 확장입니다.",
      devpulsePrimary: "VS Code Marketplace에서 Cellaxon DevPulse 보기",
    },
    flightops: {
      label: "사업 검토 / FlightOps",
      title: "현장 운영 기록과 증빙을 더 정확하게.",
      body: "현재 개념 검증 단계입니다. FlightOps는 현장 운영 기록과 보고서를 신뢰할 수 있게 관리하는 제품군으로 사업성을 검토하고 있습니다.",
      status: "개념 검증 중",
      action: "PoC 문의하기",
    },
    company: {
      label: "회사 소개",
      title: "복잡한 문제를 분명하게 풉니다.",
      body: "CELLAXON은 경기도 화성에서 소프트웨어를 만드는 회사입니다. 의사결정, 개발 과정, 현장 운영처럼 복잡한 정보를 더 쉽게 이해하고 검증할 수 있는 제품을 만듭니다.",
      addressLabel: "주소",
      address: "경기도 화성시 동탄감배산로 143, 202동 2409호",
      emailLabel: "이메일",
      phoneLabel: "전화",
      linksLabel: "외부 링크",
      shortcuts: "바로가기",
      blog: "블로그",
      linkedin: "LinkedIn",
    },
    footer: {
      line: "복잡한 일을 더 분명하게.",
      copyright: "© 2026 CELLAXON. All rights reserved.",
    },
  },
} as const;
